/**
	Generated by sails-inverse-model
	Date:Sat Sep 25 2021 00:53:11 GMT+0200 (közép-európai nyári idő)
*/

module.exports = {
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true,
    },
    name: {
      type: "string",
      columnType: "varchar",
      maxLength: 120,
      required: true,
    },
    city_id: {
      model: "city",
      required: true,
    },
    address1: {
      type: "string",
      columnType: "varchar",
      maxLength: 120,
    },
    address2: {
      type: "string",
      columnType: "varchar",
      maxLength: 120,
    },
    zip: {
      type: "string",
      columnType: "varchar",
      maxLength: 10,
    },
    createdAt: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
    },
    updatedAt: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
    },
  },
};
