/**
	Generated by sails-inverse-model
	Date:Sat Sep 25 2021 02:25:55 GMT+0200 (közép-európai nyári idő)
*/

module.exports = {
    attributes: {
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        name: {
            type: "string",
            columnType: "varchar",
            maxLength: 20,
            required: true
        },
        level: {
            type: "string",
            columnType: "enum",
            isIn: ["1", "2", "3", "4", "5"],
            required: true
        },
        description: {
            type: "string",
            columnType: "varchar",
            maxLength: 200,
            required: true
        },
        createdAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        },
        updatedAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        }
    }
};