/**
	Generated by sails-inverse-model
	Date:Sat Sep 25 2021 02:25:55 GMT+0200 (közép-európai nyári idő)
*/

module.exports = {
    attributes: {
        user_id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        role_id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        createdAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        },
        updatedAt: {
            type: "number",
            columnType: "bigint",
            isInteger: true
        }
    }
};