/**
	Generated by sails-inverse-model
	Date:Sat Sep 25 2021 02:25:55 GMT+0200 (közép-európai nyári idő)
*/

module.exports = {
  attributes: {
    user_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true,
    },
    user_id: {
      model: "user",
      required: true,
      description: "The associated user.",
    },
    shop_id: {
      model: "shop",
      required: true,
      description: "The assocuated shop.",
    },
    createdAt: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
    },
    updatedAt: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
    },
  },
};
