/**
	Generated by sails-inverse-model
	Date:Sat Sep 25 2021 02:25:55 GMT+0200 (közép-európai nyári idő)
*/

module.exports = {
  attributes: {
    user_id: {
      type: "number",
      required: true,
    },
    role_id: {
      model: "role",
      required: true,
    },
    createdAt: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
    },
    updatedAt: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
    },
  },
};
